- name: "Check monitoring deployment type | servers-monitoring"
  assert:
    that:
      node_exporter_deployment_type in ['host', 'docker']
    msg: "Monitoring support only host/docker deployment types"

- name: "Install node-exporter on host | servers-monitoring"
  import_tasks: "host.yml"
  when: node_exporter_deployment_type == "host"

- name: "Configure systemd | servers-monitoring"
  template:
    src: "node-exporter.service.j2"
    dest: "/etc/systemd/system/node-exporter.service"
    mode: 0644
  register: node_exporter_service

- name: "Reload systemd | servers-monitoring"
  systemd:
    name: "node-exporter"
    daemon_reload: true
  when: node_exporter_service.changed
  notify: restart-node-exporter

- name: "Enable end start node-exporter | servers-monitoring"
  systemd:
    name: "node-exporter"
    state: "started"
    enabled: true
  register: node_exporter_started
