- name: "Configure hostname | servers-hostname"
  hostname:
    name: "{{ inventory_hostname }}"

- name: "Add hostname to /etc/hosts | servers-hostname"
  lineinfile:
    dest: "/etc/hosts"
    regexp: ".*{{ inventory_hostname }}"
    line: "127.0.0.1 {{ inventory_hostname }}"
