# Модуль не совместим с RHEL
# https://github.com/ansible/ansible/issues/44708
- name: "Generate locale {{ item }} | servers-locales"
  locale_gen:
    name: "{{ item.name }}"
    state: "{{ item.state|default('present') }}"
  loop: "{{ locales }}"
  when: ansible_distribution in ['Debian', 'Ubuntu']
