- name: restart-node-exporter
  become: true
  systemd:
    name: "node-exporter"
    state: "restarted"
  when: not node_exporter_started.changed

- name: restart-systemd-tymesyncd
  become: true
  systemd:
    name: "systemd-timesyncd"
    state: "restarted"

- name: restart-ntpd
  become: true
  service:
    name: "{{ ntp_service_name }}"
    state: "restarted"
