---
- name: Converge
  hosts: all
  tasks:
  - name: "include ansible-servers vars"
    include_vars:
      file: "vars.yml"

  - name: "ansible-origins"
    include_role:
      name: "ansible-origins"
