repositories_apt:
- repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
  key: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
  state: "present"

extra_software:
- iotop
- nginx

extra_pip_software:
- s3cmd
- boto3

extra_sudoers_configs:
- name: "aliens"
  content: |
    aliens ALL=(ALL) ALL
- name: "predators"
  content: |
    predators ALL=(ALL) ALL

users:
- login: "anny"
  passwd: "$6$C1o0jHxqRgDsJRRU$W7kMcbL5X.rddAPgOycc1ozAhcb4QCDXzzKviJV.Y.cmhv8pmqlMVKvjQmfoJccF87LNVVd7IrQrUD3BdB5BA1"
  description: "Anny admin"
  state: "present"
  ssh_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOoy446Zovs2s/W3161VZFj1kIYTf1x2+pEW2S31TpBE anny@work"
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIPrHywZUlFqgBPpe3rz2vCB2l6Ke0KYhyDB6yAOp6dF anny@home"
  dirs:
  - dir: ".test_dir"
    mode: "0644"
  - dir: ".test_dir2"
    mode: "0700"
  configs:
  - src: |
      Config test file content
    dst: ".test_dir/test_config"
    inline: true
  groups:
  - sudo
- login: "danny"
  description: "Danny junior admin"
  shell: "zsh"
- login: "evil"
  state: "absent"

dns_servers:
- 8.8.8.8
- 1.1.1.1

dns_timeout: 10

timezone: "Europe/Moscow"

ntp_servers:
- time.google.com
- pool.ntp.org

sysctl:
  - "net.ipv4.ip_forward=1"
