- name: "Check /etc/motd | servers-motd"
  stat:
    path: "/etc/motd"
  register: motd_stat

- name: "Update motd | servers-motd"
  template:
    src: "motd/motd.j2"
    dest: "/etc/motd"
    mode: "0644"
  when: motd_stat.stat.exists
