- name: "Create 00-header | servers-user"
  template:
    src: "motd/{{ item }}.j2"
    dest: "/etc/update-motd.d/{{ item }}"
    mode: "0755"
  with_items:
    - "00-header"
    - "10-common"

- name: "Delete 10-help-text | servers-user"
  file:
    path: "/etc/update-motd.d/{{ item }}"
    state: "absent"
  with_items:
    - "10-help-text"
    - "10-uname"
    - "51-cloudguest"
    - "50-motd-news"
    - "60-unminimize"
